# Generated by Django 3.2.7 on 2023-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testmodel_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='testmodel',
        ),
    ]
